####  Understanding Numpy    
- A library for mathematical computations
- Never used in isolation,  but is mostly used together with pandas, statsmodel, and other visualization libraries like matplotlib   
- Significant for operating mathematics on lists(called arrays in Numpy)
- It also saves on space making computations fast and effecient compared to when using standard python

  ###### Significant in:    
  a. Efficient numeric computation with C primitives            
  b. Efficient collections with vectorized operations    
  c. An integrated and natural Linear Algebra API    
  d. A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.    


#### Practising Numpy  

In [26]:
import numpy as np
import matplotlib.pyplot as plt

### Generating an Array   
An array refers to a list in numpy   
An array is made using np.array() for specific numbers    
An array can also be made using np.arange() for a given range of numbers    
np.random is a submodule of NumPy that provides functions for generating random numbers for different probability distribution namely:  
>a. uniform   
 b. normal   
 c. binomial

In [25]:
#generate a list with numbers 
a = np.array([1,3,4,58,94])

#generate an array with range 0 to5 
b = np.arange(6)

#generate random numbers range 10
#uniform distribution
c = np.random.rand(1,10)

#normal(mean, variance)
d= np.random.rand(4,3)

#binomal distribution (low, high)
e =np.random.randint(2,7)
print("a:",a,"\n", "b:", b,"\n","c:",c,"\n","d:", d,"\n","e:",e)

a: [ 1  3  4 58 94] 
 b: [0 1 2 3 4 5] 
 c: [[0.61505814 0.16290652 0.85368552 0.0257049  0.07214341 0.50754823
  0.94965498 0.2566482  0.0152932  0.38367669]] 
 d: [[0.7912527  0.82882112 0.07884096]
 [0.60121491 0.60657969 0.22437696]
 [0.17915063 0.92477653 0.77174724]
 [0.62208951 0.31391432 0.38061206]] 
 e: 6


### Slicing: Indexing in Numpy   
Indices refers to positioning of elements in an array   
Indices start with zero  
Slicing works in arrays in the same way as in lists   

In [44]:
#hands on using array created in variable a
#first, third, and last element in array a
a[0], a[4],a[-1]

(1, 94, 94)

In [45]:
##indexing a range (slicing)
#elements in range 2 to 4 in array a
a[3:5]

array([58, 94])

In [47]:
# all elements in the entire row of the array
a[:]

array([ 1,  3,  4, 58, 94])

### Understanding Data structures in Numpy Array    
a. Data type: dtype    
d. Dimensionality: ndim          
c. data size: size   
d. Shape of data: .shape   

In [53]:
#using array b as an example
print("Shape of b", b.shape,"\n","Dimensions of b:", b.ndim,"\n", "Size of array b:", b.size, "\n","Data type of array b:", b.dtype)


Shape of b (6,) 
 Dimensions of b: 1 
 Size of array b: 6 
 Data type of array b: int32


In [67]:
#create arrays with desired shape and datatype
#Array f with datatype integer64
f =np.arange(6,dtype=np.int64)

#array g with float
g = np.arange(7, dtype = float)
f,"\n", g

(array([0, 1, 2, 3, 4, 5], dtype=int64),
 '\n',
 array([0., 1., 2., 3., 4., 5., 6.]))

In [75]:
#Create a numpy array of size 4, filled with zeros
array = np.array([0]*4)
array, "size:", array.size

(array([0, 0, 0, 0]), 'size:', 4)

In [77]:
#Create a numpy array with values ranging from 5 to 30
array = np.arange(5,31)
array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
#Create a numpy matrix of 3*3 integers, filled with ones.
matrix_3by3 = np.ones([3,3], dtype = np.int32)
matrix_3by3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])