## Numpy: Matrices, Shapes, and Dimensions

In [2]:
#import numpy
import numpy as np

### Data structures

In [5]:
#Create a matrix ofa any numbers of your choice

matrix = np.array([[1,7,8,9],[4,6,78,2],[1,4,2,34]])
matrix

array([[ 1,  7,  8,  9],
       [ 4,  6, 78,  2],
       [ 1,  4,  2, 34]])

In [11]:
#Check dimension, size, type, and shape of the matrix
print("Dimension:", matrix.ndim, "\n", "Type:", matrix.dtype, "\n","Size:", matrix.size,"\n","Shape:", matrix.shape)

Dimension: 2 
 Type: int32 
 Size: 12 
 Shape: (3, 4)


### Slicing and Indexing 

Rows: `matrix[n:m]`, this gives the range of elements in the nth row and the (m-1)th row   
Columns: `matrix[a:b]`, this gives the range of elements in the ath columnn and the (b-1)th column   
Single row and column: `matrix[n][b]`  nth row and bth column   
Rows and columns : `matrix[m:n,a:b]`

In [ ]:
# display first row

In [17]:
matrix[0]

array([1, 7, 8, 9])

In [18]:
#display all rows
matrix[:]

array([[ 1,  7,  8,  9],
       [ 4,  6, 78,  2],
       [ 1,  4,  2, 34]])

In [20]:
#display second row
matrix[1]

array([ 4,  6, 78,  2])

In [35]:
#display first two rows, and second and third row
print("First two rows:", matrix[0:2])
print("third and fourth row:", matrix[1:])

First two rows: [[ 1  7  8  9]
 [ 4  6 78  2]]
third and fourth row: [[ 4  6 78  2]
 [ 1  4  2 34]]


In [46]:
#display element in first row second column
print("First row-second column", matrix[0][1])

#display element in third row, fourth column
print("Element, Third row-Fourth column", matrix [2][3])

First row-second column 7
Element, Third row-Fourth column 34


In [43]:
#display elements in first colummn, and third column
print("Elements in first column", matrix[:, 0:1])
print("Elements in third column", matrix[:, 3:4])

Elements in first column [[1]
 [4]
 [1]]
Elements in third column [[ 9]
 [ 2]
 [34]]


In [45]:
#display elements in the first two rows , first two columns
matrix[:2,:2]

array([[1, 7],
       [4, 6]])